### ISSUE TITLE
addComment можно сделать проще

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [AnatoliiZagadaev/-PortfolioSite#2]
У `textarea` так же есть пропс `onChange` если пробросить туда функцию она будет вызываться при каждом изменении текст и в параметрах можно будет получить это значение. Ref это не лучший способ получить значение
После чего тебе нужно будет сохранить полученное значение в state. И это же значение из стейта пробросить обратно в `textarea` в пропс `value`

Пара примеров: https://ru.reactjs.org/docs/forms.html#the-textarea-tag

Если что - пиши в слаке, может подскажу что-то)

**Comment by AnatoliiZagadaev** [comment]
Дякую, зайві зображення видалив

**Comment by AnatoliiZagadaev** [comment]
Виправив
