### ISSUE TITLE
Регистрозависимость

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [AnatoliiZagadaev/-PortfolioSite#22]
В большинстве ОС важно с большой или с маленькой буквы записано название файлов и папок (кроме Windows). А вот почти все сервера на linux. Поэтому в import должен быть точный путь. А у тебя `components` и `pages` называются с большой буквы а в import с маленькой

**Comment by DmitriiMelnikOnix** [comment]
Если переименовать папки чтобы были с маленькой буквы, тогда все работает

**Comment by AnatoliiZagadaev** [comment]
Виправив

**Comment by AnatoliiZagadaev** [comment]
Виправив
